name: AgenticOps CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # ✅ Simulated GPU Test Block
    - name: Simulate GPU Model Test
      run: |
        echo ">>> Running simulated GPU test"
        python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
        python tests/test_model_gpu.py || echo 'GPU test failed' > tests/output_logs/gpu_test_log.txt
      continue-on-error: true

    # ✅ Vectorstore test
    - name: Test Vectorstore Build
      run: |
        python tests/test_vectorstore.py

    # ✅ Regression testing on logs
    - name: Regression Log Analysis
      run: |
        pytest tests/test_logs_regression.py

    # ✅ Check reproducibility (FAISS, etc.)
    - name: Artifact Determinism Check
      run: |
        python tests/test_artifact_hash.py

    # ✅ Archive logs for AgenticOps
    - name: Archive CI Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: agenticops-logs
        path: tests/output_logs/
